// cardsData.js - Données des cartes Monopoly Star Wars
const cardsData = [
    { id: 1, stars: 1, isGold: false, name: "Sortie ciné" },
    { id: 2, stars: 1, isGold: false, name: "Fan galactique" },
    { id: 3, stars: 1, isGold: false, name: "Trésors sur cassette" },
    { id: 4, stars: 1, isGold: false, name: "Un film épique" },
    { id: 5, stars: 1, isGold: false, name: "Sidération" },
    { id: 6, stars: 1, isGold: false, name: "Nouveau message" },
    { id: 7, stars: 1, isGold: false, name: "Mon seul espoir" },
    { id: 8, stars: 1, isGold: false, name: "Premier sabre" },
    { id: 9, stars: 1, isGold: false, name: "Rêves galactiques" },
    { id: 10, stars: 1, isGold: false, name: "Temple Jedi" },
    { id: 11, stars: 1, isGold: false, name: "Pouvoir inné" },
    { id: 12, stars: 1, isGold: false, name: "Corridors sacrés" },
    { id: 13, stars: 1, isGold: false, name: "Cristaux brillants" },
    { id: 14, stars: 1, isGold: false, name: "Force méditative" },
    { id: 15, stars: 1, isGold: false, name: "Entraînement martial" },
    { id: 16, stars: 1, isGold: false, name: "Savoirs inaccessibles" },
    { id: 17, stars: 1, isGold: false, name: "Force & détermination" },
    { id: 18, stars: 2, isGold: false, name: "Enfin Padawans" },
    { id: 19, stars: 1, isGold: false, name: "Doux foyer" },
    { id: 20, stars: 1, isGold: false, name: "Escapade ensablée" },
    { id: 21, stars: 1, isGold: false, name: "En repérage" },
    { id: 22, stars: 1, isGold: false, name: "Écrou défaillant" },
    { id: 23, stars: 1, isGold: false, name: "Bain d'huile" },
    { id: 24, stars: 1, isGold: false, name: "Le Mos est à la fête" },
    { id: 25, stars: 1, isGold: false, name: "Soirée à la cantina" },
    { id: 26, stars: 2, isGold: false, name: "Lait de bantha" },
    { id: 27, stars: 2, isGold: false, name: "Coucher des soleils" },
    { id: 28, stars: 1, isGold: false, name: "Grande Arène" },
    { id: 29, stars: 1, isGold: false, name: "Casse-croûte de Hutt" },
    { id: 30, stars: 1, isGold: false, name: "Bien calibré" },
    { id: 31, stars: 1, isGold: false, name: "En concurrence" },
    { id: 32, stars: 1, isGold: false, name: "Sabotage" },
    { id: 33, stars: 1, isGold: false, name: "On s'équipe" },
    { id: 34, stars: 2, isGold: false, name: "Prêts, foncez !" },
    { id: 35, stars: 2, isGold: false, name: "Victoire serrée" },
    { id: 36, stars: 2, isGold: false, name: "Magnats des modules" },
    { id: 37, stars: 1, isGold: false, name: "Soir de première" },
    { id: 38, stars: 1, isGold: false, name: "Entrée remarquée" },
    { id: 39, stars: 1, isGold: false, name: "Symphonie spatiale" },
    { id: 40, stars: 1, isGold: false, name: "Sous les néons" },
    { id: 41, stars: 1, isGold: false, name: "Cité des nuages" },
    { id: 42, stars: 2, isGold: false, name: "La grande vie sur Bespin" },
    { id: 43, stars: 2, isGold: false, name: "Abondance céleste" },
    { id: 44, stars: 2, isGold: false, name: "À vos dés" },
    { id: 45, stars: 3, isGold: false, name: "Lancer chanceux" },
    { id: 46, stars: 1, isGold: false, name: "Schémas" },
    { id: 47, stars: 1, isGold: false, name: "Sous la neige" },
    { id: 48, stars: 1, isGold: false, name: "Projection gelée" },
    { id: 49, stars: 2, isGold: false, name: "Hangar de Hoth" },
    { id: 50, stars: 2, isGold: false, name: "Encore perdus" },
    { id: 51, stars: 2, isGold: false, name: "Signal localisé" },
    { id: 52, stars: 2, isGold: false, name: "Système rétabli" },
    { id: 53, stars: 2, isGold: false, name: "Rebelles honoraires" },
    { id: 54, stars: 3, isGold: false, name: "Copain à fourrure" },
    { id: 55, stars: 1, isGold: false, name: "Accueil en or !" },
    { id: 56, stars: 1, isGold: false, name: "Prête à servir" },
    { id: 57, stars: 1, isGold: false, name: "Révérence royale" },
    { id: 58, stars: 2, isGold: false, name: "Pour l'Alliance" },
    { id: 59, stars: 2, isGold: false, name: "Chignons cultes" },
    { id: 60, stars: 2, isGold: false, name: "Parée à décoller" },
    { id: 61, stars: 2, isGold: false, name: "Poste de commande" },
    { id: 62, stars: 3, isGold: false, name: "As des pilotes" },
    { id: 63, stars: 3, isGold: false, name: "Le triomphe !" },
    { id: 64, stars: 1, isGold: false, name: "Village perché" },
    { id: 65, stars: 1, isGold: false, name: "Culte du droïde" },
    { id: 66, stars: 2, isGold: false, name: "Marcheur vaincu" },
    { id: 67, stars: 2, isGold: false, name: "Le cuir, c'est in" },
    { id: 68, stars: 2, isGold: false, name: "Coup de filet" },
    { id: 69, stars: 2, isGold: false, name: "Vite en haut !" },
    { id: 70, stars: 2, isGold: false, name: "Peg-E le Grand" },
    { id: 71, stars: 3, isGold: false, name: "Deltaplanant !" },
    { id: 72, stars: 3, isGold: false, name: "Fête au feu de camp" },
    { id: 73, stars: 1, isGold: false, name: "Sanctuaire du marais" },
    { id: 74, stars: 2, isGold: false, name: "Présentation du sage" },
    { id: 75, stars: 2, isGold: false, name: "Leçons pesantes" },
    { id: 76, stars: 2, isGold: false, name: "Concentration" },
    { id: 77, stars: 2, isGold: false, name: "Épreuves du magnat" },
    { id: 78, stars: 3, isGold: false, name: "Dark Ronrons" },
    { id: 79, stars: 3, isGold: false, name: "Chatpristi" },
    { id: 80, stars: 3, isGold: false, name: "Maître de la Force" },
    { id: 81, stars: 3, isGold: false, name: "Chevalier Jedi" },
    { id: 82, stars: 2, isGold: false, name: "QG de Hutt" },
    { id: 83, stars: 2, isGold: false, name: "L'offre de Jabba" },
    { id: 84, stars: 2, isGold: false, name: "Sacré coquin" },
    { id: 85, stars: 2, isGold: false, name: "Mode esclave" },
    { id: 86, stars: 2, isGold: false, name: "Mets délicats ?" },
    { id: 87, stars: 3, isGold: false, name: "Barge à voiles" },
    { id: 88, stars: 3, isGold: false, name: "Spectacle de l'esquif" },
    { id: 89, stars: 3, isGold: false, name: "Charmeur de rancor" },
    { id: 90, stars: 3, isGold: false, name: "Groupe de Max Rebo" },
    { id: 91, stars: 2, isGold: false, name: "Les mécanos" },
    { id: 92, stars: 2, isGold: false, name: "Bon p'tit gars" },
    { id: 93, stars: 2, isGold: false, name: "Briefing de mission" },
    { id: 94, stars: 2, isGold: false, name: "Alerte rouge !" },
    { id: 95, stars: 3, isGold: false, name: "Emberlificoté" },
    { id: 96, stars: 3, isGold: false, name: "Vol X-trême" },
    { id: 97, stars: 3, isGold: false, name: "Bricoleuse astucieuse" },
    { id: 98, stars: 3, isGold: false, name: "L'esprit de la Résistance" },
    { id: 99, stars: 4, isGold: false, name: "Décorés" },
    { id: 100, stars: 2, isGold: false, name: "Arrivée impériale" },
    { id: 101, stars: 2, isGold: false, name: "Quel choc !" },
    { id: 102, stars: 2, isGold: false, name: "Frais galactiques" },
    { id: 103, stars: 3, isGold: false, name: "Minet impérial" },
    { id: 104, stars: 3, isGold: false, name: "Empire de magnat" },
    { id: 105, stars: 3, isGold: false, name: "Vador jaloux" },
    { id: 106, stars: 3, isGold: false, name: "Édition Sith" },
    { id: 107, stars: 3, isGold: false, name: "Rivalité féroce" },
    { id: 108, stars: 4, isGold: false, name: "Le dernier adieu" },
    { id: 109, stars: 2, isGold: false, name: "Facéties kowakiennes" },
    { id: 110, stars: 2, isGold: false, name: "Cadeau de bantha" },
    { id: 111, stars: 3, isGold: false, name: "Sieste du tooka" },
    { id: 112, stars: 3, isGold: false, name: "Balade du blurrg" },
    { id: 113, stars: 3, isGold: false, name: "Nuée de mynocks" },
    { id: 114, stars: 3, isGold: false, name: "Copains porgs" },
    { id: 115, stars: 3, isGold: false, name: "Anges de wampa" },
    { id: 116, stars: 4, isGold: false, name: "Tauntaun tout câlin" },
    { id: 117, stars: 4, isGold: false, name: "Purggils en chasse" },
    { id: 118, stars: 2, isGold: false, name: "Visite sableuse" },
    { id: 119, stars: 2, isGold: false, name: "Objets trouvés" },
    { id: 120, stars: 3, isGold: false, name: "La réparatrice" },
    { id: 121, stars: 3, isGold: false, name: "Mets raffinés" },
    { id: 122, stars: 3, isGold: false, name: "Jour de marché" },
    { id: 123, stars: 3, isGold: false, name: "Client du désert" },
    { id: 124, stars: 4, isGold: false, name: "Jackpot Jawa" },
    { id: 125, stars: 4, isGold: false, name: "Une des nôtres" },
    { id: 126, stars: 4, isGold: false, name: "Utinni et au revoir !" },
    { id: 127, stars: 2, isGold: false, name: "Quai 94" },
    { id: 128, stars: 3, isGold: false, name: "Han le héros" },
    { id: 129, stars: 3, isGold: false, name: "Prêts pour le saut" },
    { id: 130, stars: 3, isGold: false, name: "Cargaison secrète" },
    { id: 131, stars: 3, isGold: false, name: "Holo-échecs" },
    { id: 132, stars: 4, isGold: false, name: "Erreur du blaster" },
    { id: 133, stars: 4, isGold: false, name: "Assaut de chatouilles" },
    { id: 134, stars: 4, isGold: true, name: "Chaude fourrure" },
    { id: 135, stars: 5, isGold: false, name: "Direction l'hyperespace" },
    { id: 136, stars: 3, isGold: false, name: "Base Starkiller" },
    { id: 137, stars: 3, isGold: false, name: "Mission de sauvetage" },
    { id: 138, stars: 3, isGold: false, name: "La voie est libre" },
    { id: 139, stars: 3, isGold: false, name: "Faire diversion" },
    { id: 140, stars: 4, isGold: false, name: "Piratage du système" },
    { id: 141, stars: 4, isGold: false, name: "Divine bonté du Ciel !" },
    { id: 142, stars: 4, isGold: true, name: "En mode furtif" },
    { id: 143, stars: 5, isGold: false, name: "Déguis-E" },
    { id: 144, stars: 5, isGold: false, name: "Fuite réussie" },
    { id: 145, stars: 3, isGold: false, name: "Nouvelle amie" },
    { id: 146, stars: 3, isGold: false, name: "Amateurs de baballes" },
    { id: 147, stars: 3, isGold: false, name: "Pas touche !" },
    { id: 148, stars: 4, isGold: false, name: "Magnat miniature" },
    { id: 149, stars: 4, isGold: false, name: "Curiosité compacte" },
    { id: 150, stars: 4, isGold: true, name: "Côte à côte" },
    { id: 151, stars: 5, isGold: false, name: "Force grandissante" },
    { id: 152, stars: 5, isGold: false, name: "Beskar de pointe" },
    { id: 153, stars: 5, isGold: true, name: "Mandalorienne" },
    { id: 154, stars: 3, isGold: false, name: "Accueil de Vador" },
    { id: 155, stars: 4, isGold: false, name: "Avec style" },
    { id: 156, stars: 4, isGold: false, name: "Pique-nique Sith" },
    { id: 157, stars: 4, isGold: false, name: "Force et baballe" },
    { id: 158, stars: 4, isGold: true, name: "Dark volley" },
    { id: 159, stars: 5, isGold: false, name: "Allergie au soleil" },
    { id: 160, stars: 5, isGold: false, name: "Barbecue obscur" },
    { id: 161, stars: 5, isGold: false, name: "Adieux fumants" },
    { id: 162, stars: 5, isGold: true, name: "Lien galactique" },
    { id: 163, stars: 4, isGold: false, name: "Kashyyyk" },
    { id: 164, stars: 4, isGold: false, name: "Accueil chaleureux" },
    { id: 165, stars: 4, isGold: false, name: "Mini Wookiee" },
    { id: 166, stars: 4, isGold: false, name: "Holo-visio" },
    { id: 167, stars: 4, isGold: true, name: "Brushing de Chewie" },
    { id: 168, stars: 5, isGold: false, name: "Tout p'tit Wookie" },
    { id: 169, stars: 5, isGold: false, name: "Dans le mille" },
    { id: 170, stars: 5, isGold: true, name: "Sous les galaxies" },
    { id: 171, stars: 5, isGold: true, name: "Salutations poilues" },
    { id: 172, stars: 4, isGold: false, name: "X-wing" },
    { id: 173, stars: 4, isGold: false, name: "Destroyer stellaire" },
    { id: 174, stars: 4, isGold: false, name: "Chasseur TIE de Dark Vador" },
    { id: 175, stars: 4, isGold: true, name: "Char des sables" },
    { id: 176, stars: 5, isGold: false, name: "Étoile de la Mort" },
    { id: 177, stars: 5, isGold: false, name: "Landspeeder X-34" },
    { id: 178, stars: 5, isGold: true, name: "Chasseur TIE" },
    { id: 179, stars: 5, isGold: true, name: "TB-TT" },
    { id: 180, stars: 5, isGold: true, name: "Faucon Millenium" },
    { id: 181, stars: 4, isGold: false, name: "Bisou d'eopie" },
    { id: 182, stars: 4, isGold: false, name: "Retour sur Terre" },
    { id: 183, stars: 5, isGold: false, name: "Fans absolus" },
    { id: 184, stars: 5, isGold: false, name: "Force-corn" },
    { id: 185, stars: 5, isGold: false, name: "Maître des goodies" },
    { id: 186, stars: 5, isGold: true, name: "Concours de répliques" },
    { id: 187, stars: 5, isGold: true, name: "Crédits de fin" },
    { id: 188, stars: 5, isGold: true, name: "Buffet spatial" },
    { id: 189, stars: 5, isGold: true, name: "Selfie stellaire" },
    { id: 190, stars: 4, isGold: true, name: "Luke Skywalker" },
    { id: 191, stars: 4, isGold: true, name: "Princesse Leia" },
    { id: 192, stars: 4, isGold: true, name: "Han Solo" },
    { id: 193, stars: 4, isGold: true, name: "Chewbacca" },
    { id: 194, stars: 4, isGold: true, name: "Yoda" },
    { id: 195, stars: 4, isGold: true, name: "R2-D2" },
    { id: 196, stars: 4, isGold: true, name: "BB-8" },
    { id: 197, stars: 4, isGold: true, name: "Le Mandalorien" },
    { id: 198, stars: 4, isGold: true, name: "Grogu" },
    { id: 199, stars: 3, isGold: false, name: "L'Empire a besoin de toi" },
    { id: 200, stars: 3, isGold: false, name: "Académie impériale" },
    { id: 201, stars: 4, isGold: false, name: "Duel galactique" },
    { id: 202, stars: 4, isGold: false, name: "Dodo en classe" },
    { id: 203, stars: 4, isGold: true, name: "Gribouillages" },
    { id: 204, stars: 5, isGold: false, name: "Manquer la cible" },
    { id: 205, stars: 5, isGold: false, name: "Chatpatine" },
    { id: 206, stars: 5, isGold: true, name: "Mini-Stormtrooper" },
    { id: 207, stars: 5, isGold: true, name: "L'école est finie" },
    { id: 208, stars: 4, isGold: false, name: "Un accueil royal" },
    { id: 209, stars: 4, isGold: false, name: "C'est pas à toi" },
    { id: 210, stars: 4, isGold: false, name: "Pas si facile" },
    { id: 211, stars: 4, isGold: true, name: "Rencontre aquatique" },
    { id: 212, stars: 4, isGold: true, name: "Haute couture Gungan" },
    { id: 213, stars: 5, isGold: false, name: "Boss Nass" },
    { id: 214, stars: 5, isGold: false, name: "Repas aquatique" },
    { id: 215, stars: 5, isGold: true, name: "Balade sous la mer" },
    { id: 216, stars: 5, isGold: true, name: "Tir allié" },
    { id: 217, stars: 4, isGold: false, name: "Explorateurs de Niima" },
    { id: 218, stars: 4, isGold: false, name: "Marchand de bestioles" },
    { id: 219, stars: 4, isGold: true, name: "Plein à craquer" },
    { id: 220, stars: 4, isGold: true, name: "Reliques rebelles" },
    { id: 221, stars: 5, isGold: false, name: "Pas de notice de montage" },
    { id: 222, stars: 5, isGold: false, name: "Sable glissant" },
    { id: 223, stars: 5, isGold: true, name: "Épave" },
    { id: 224, stars: 5, isGold: true, name: "Connexion directe" },
    { id: 225, stars: 5, isGold: true, name: "Planète Haut-de-forme" },
    { id: 226, stars: 4, isGold: true, name: "Échange secret" },
    { id: 227, stars: 4, isGold: true, name: "Folle virée" },
    { id: 228, stars: 4, isGold: true, name: "Holo-plans" },
    { id: 229, stars: 5, isGold: false, name: "Cœur.exe" },
    { id: 230, stars: 5, isGold: false, name: "L'Œil d'Aldhani" },
    { id: 231, stars: 5, isGold: false, name: "Infiltration" },
    { id: 232, stars: 5, isGold: true, name: "Qu'est-ce que c'est ?!" },
    { id: 233, stars: 5, isGold: true, name: "Le coffre-fort !" },
    { id: 234, stars: 5, isGold: true, name: "Braquage réussi !" }
];