// cardsData.js - Données des cartes Monopoly GO - Nouvel Album
const cardsData = [
    { id: 1, stars: 1, isGold: false, name: "Sentier alpin" },
    { id: 2, stars: 1, isGold: false, name: "Cervin" },
    { id: 3, stars: 1, isGold: false, name: "Plaisir du parapente" },
    { id: 4, stars: 1, isGold: false, name: "Filles des alpages" },
    { id: 5, stars: 1, isGold: false, name: "Mélodie alpine" },
    { id: 6, stars: 1, isGold: false, name: "Roi des falaises" },
    { id: 7, stars: 1, isGold: false, name: "Fondue suisse" },
    { id: 8, stars: 1, isGold: false, name: "Cyclistes des montagnes" },
    { id: 9, stars: 1, isGold: false, name: "Festival folklorique" },
    { id: 10, stars: 1, isGold: false, name: "Oasis du jardin" },
    { id: 11, stars: 1, isGold: false, name: "Pique-nique préparé" },
    { id: 12, stars: 1, isGold: false, name: "Pile de casse-croûtes" },
    { id: 13, stars: 1, isGold: false, name: "Le jeu de poches" },
    { id: 14, stars: 1, isGold: false, name: "Battements d'ailes" },
    { id: 15, stars: 1, isGold: false, name: "Voleurs de pique-nique" },
    { id: 16, stars: 1, isGold: false, name: "Nain d'été" },
    { id: 17, stars: 1, isGold: false, name: "Ami fuchsia" },
    { id: 18, stars: 2, isGold: false, name: "Moulin à vent" },
    { id: 19, stars: 1, isGold: false, name: "Short de bain" },
    { id: 20, stars: 1, isGold: false, name: "Crème solaire" },
    { id: 21, stars: 1, isGold: false, name: "Chapeau d'été" },
    { id: 22, stars: 1, isGold: false, name: "Lunettes de soleil" },
    { id: 23, stars: 1, isGold: false, name: "Parasol" },
    { id: 24, stars: 1, isGold: false, name: "Glacière" },
    { id: 25, stars: 1, isGold: false, name: "Seau de plage" },
    { id: 26, stars: 2, isGold: false, name: "Ballon de plage" },
    { id: 27, stars: 2, isGold: false, name: "Serviette" },
    { id: 28, stars: 1, isGold: false, name: "Lizzie se prélasse" },
    { id: 29, stars: 1, isGold: false, name: "Chef-d'œuvre de sable" },
    { id: 30, stars: 1, isGold: false, name: "Est-ce comfortable ?" },
    { id: 31, stars: 1, isGold: false, name: "M. Triton" },
    { id: 32, stars: 1, isGold: false, name: "Surveillance de plage" },
    { id: 33, stars: 1, isGold: false, name: "Beauté de plage" },
    { id: 34, stars: 2, isGold: false, name: "Frappe calculée" },
    { id: 35, stars: 2, isGold: false, name: "Voleur de chips" },
    { id: 36, stars: 2, isGold: false, name: "Pirouettes à gogo" },
    { id: 37, stars: 1, isGold: false, name: "Montage du télescope" },
    { id: 38, stars: 1, isGold: false, name: "Chocolat cosmique" },
    { id: 39, stars: 1, isGold: false, name: "Repos mérité" },
    { id: 40, stars: 1, isGold: false, name: "Des étoiles dans les yeux" },
    { id: 41, stars: 2, isGold: false, name: "Étoiles du magnat" },
    { id: 42, stars: 2, isGold: false, name: "Un chouette hibou" },
    { id: 43, stars: 2, isGold: false, name: "Voyage étoilé" },
    { id: 44, stars: 2, isGold: false, name: "Carte des étoiles" },
    { id: 45, stars: 2, isGold: false, name: "Pluie de météores" },
    { id: 46, stars: 1, isGold: false, name: "Cabines de plage" },
    { id: 47, stars: 1, isGold: false, name: "Installation du transat" },
    { id: 48, stars: 1, isGold: false, name: "Chasseur de vagues" },
    { id: 49, stars: 2, isGold: false, name: "Sablesationnel" },
    { id: 50, stars: 2, isGold: false, name: "Douceurs de plage" },
    { id: 51, stars: 2, isGold: false, name: "Parapluie improvisé" },
    { id: 52, stars: 2, isGold: false, name: "Après la pluie" },
    { id: 53, stars: 2, isGold: false, name: "Fish & Chips" },
    { id: 54, stars: 3, isGold: false, name: "Heure dorée" },
    { id: 55, stars: 1, isGold: false, name: "Chien mouillé" },
    { id: 56, stars: 1, isGold: false, name: "Trésor enfoui" },
    { id: 57, stars: 2, isGold: false, name: "Journée Spa" },
    { id: 58, stars: 2, isGold: false, name: "En vadrouille" },
    { id: 59, stars: 2, isGold: false, name: "Stand canin" },
    { id: 60, stars: 2, isGold: false, name: "Toutou à bord" },
    { id: 61, stars: 2, isGold: false, name: "Empreintes de sable" },
    { id: 62, stars: 3, isGold: false, name: "Retour à la maison" },
    { id: 63, stars: 3, isGold: false, name: "L'heure de la sieste" },
    { id: 64, stars: 1, isGold: false, name: "Feux d'artifice" },
    { id: 65, stars: 2, isGold: false, name: "Étincelles en folie" },
    { id: 66, stars: 2, isGold: false, name: "Drapeaux étoilés" },
    { id: 67, stars: 2, isGold: false, name: "Héros de la customisation" },
    { id: 68, stars: 2, isGold: false, name: "Barbecue d'été" },
    { id: 69, stars: 3, isGold: false, name: "Rouge, blanc et miam" },
    { id: 70, stars: 3, isGold: false, name: "Salut céleste" },
    { id: 71, stars: 3, isGold: false, name: "Feux-tastique" },
    { id: 72, stars: 3, isGold: false, name: "Ne pas déranger" },
    { id: 73, stars: 2, isGold: false, name: "C'est parti !" },
    { id: 74, stars: 2, isGold: false, name: "Pommes d'amour" },
    { id: 75, stars: 2, isGold: false, name: "Chamboule tout" },
    { id: 76, stars: 2, isGold: false, name: "Stand de lots" },
    { id: 77, stars: 2, isGold: false, name: "Champion des hot-dogs" },
    { id: 78, stars: 3, isGold: false, name: "La grande roue" },
    { id: 79, stars: 3, isGold: false, name: "Chevauchée du carrousel" },
    { id: 80, stars: 3, isGold: false, name: "Barbe à papa" },
    { id: 81, stars: 4, isGold: false, name: "Dernière récolte" },
    { id: 82, stars: 2, isGold: false, name: "Ciels d'Aloha" },
    { id: 83, stars: 2, isGold: false, name: "Surfe sur la vague !" },
    { id: 84, stars: 2, isGold: false, name: "Touristes tortues" },
    { id: 85, stars: 2, isGold: false, name: "Canoë à plusieurs" },
    { id: 86, stars: 3, isGold: false, name: "Mélodie tropicale" },
    { id: 87, stars: 3, isGold: false, name: "Collier de fleurs" },
    { id: 88, stars: 3, isGold: false, name: "Douceurs tropicales" },
    { id: 89, stars: 3, isGold: false, name: "Le hula" },
    { id: 90, stars: 4, isGold: false, name: "Danse du feu" },
    { id: 91, stars: 2, isGold: false, name: "Camion de glaces" },
    { id: 92, stars: 2, isGold: false, name: "Icône glacée" },
    { id: 93, stars: 3, isGold: false, name: "Spirale géante" },
    { id: 94, stars: 3, isGold: false, name: "Bol de joie" },
    { id: 95, stars: 3, isGold: false, name: "Cerise sur le gâteau" },
    { id: 96, stars: 3, isGold: false, name: "Cornetman" },
    { id: 97, stars: 3, isGold: false, name: "Saveurs inexplorées" },
    { id: 98, stars: 4, isGold: false, name: "Erreur glaciale" },
    { id: 99, stars: 4, isGold: false, name: "Cadre gelé" },
    { id: 100, stars: 2, isGold: false, name: "Fraisement fan" },
    { id: 101, stars: 2, isGold: false, name: "Joie du défilé" },
    { id: 102, stars: 3, isGold: false, name: "Marchandises primées" },
    { id: 103, stars: 3, isGold: false, name: "Reine des fraises" },
    { id: 104, stars: 3, isGold: false, name: "Bonheur fruité" },
    { id: 105, stars: 3, isGold: false, name: "Fraîchement cuit" },
    { id: 106, stars: 4, isGold: false, name: "Mongolfraise" },
    { id: 107, stars: 4, isGold: false, name: "Fraise à roulette" },
    { id: 108, stars: 4, isGold: true, name: "Dites fraises !" },
    { id: 109, stars: 2, isGold: false, name: "Mât de mai" },
    { id: 110, stars: 3, isGold: false, name: "Couronnes de fleurs" },
    { id: 111, stars: 3, isGold: false, name: "Bouquet d'été" },
    { id: 112, stars: 3, isGold: false, name: "Vallée fleuries" },
    { id: 113, stars: 3, isGold: false, name: "Buffet scandinave" },
    { id: 114, stars: 4, isGold: false, name: "Reine du mât de mai" },
    { id: 115, stars: 4, isGold: false, name: "Le jeu de Kubb" },
    { id: 116, stars: 4, isGold: false, name: "Jordgubbstårta" },
    { id: 117, stars: 4, isGold: true, name: "Fête des pétales" },
    { id: 118, stars: 3, isGold: false, name: "Hola Oaxaca" },
    { id: 119, stars: 3, isGold: false, name: "Boissons sucrées" },
    { id: 120, stars: 3, isGold: false, name: "Guelaguetza" },
    { id: 121, stars: 3, isGold: false, name: "L'heure des tacos !" },
    { id: 122, stars: 4, isGold: false, name: "Défilé des marionettes" },
    { id: 123, stars: 4, isGold: false, name: "Jouer ensemble" },
    { id: 124, stars: 4, isGold: false, name: "Trouvailles textiles" },
    { id: 125, stars: 4, isGold: true, name: "Marmota" },
    { id: 126, stars: 5, isGold: false, name: "Souvenirs de Oaxaca" },
    { id: 127, stars: 3, isGold: false, name: "Arrivée à la colo" },
    { id: 128, stars: 3, isGold: false, name: "Prêt ou pas" },
    { id: 129, stars: 3, isGold: false, name: "Boulet de canon !" },
    { id: 130, stars: 4, isGold: false, name: "Tir" },
    { id: 131, stars: 4, isGold: false, name: "À la" },
    { id: 132, stars: 4, isGold: false, name: "Corde" },
    { id: 133, stars: 4, isGold: true, name: "Soirée s'mores" },
    { id: 134, stars: 5, isGold: false, name: "Chemin du crépuscule" },
    { id: 135, stars: 5, isGold: true, name: "Meilleurs amis" },
    { id: 136, stars: 3, isGold: false, name: "Sur la route" },
    { id: 137, stars: 3, isGold: false, name: "Robot perdu" },
    { id: 138, stars: 4, isGold: false, name: "Par ici" },
    { id: 139, stars: 4, isGold: false, name: "Cadillac Ranch" },
    { id: 140, stars: 4, isGold: false, name: "Délice du diner" },
    { id: 141, stars: 4, isGold: true, name: "Problème de pneu" },
    { id: 142, stars: 5, isGold: false, name: "Les ânes d'Oatman" },
    { id: 143, stars: 5, isGold: false, name: "Nuits californiennes" },
    { id: 144, stars: 5, isGold: true, name: "Fauteuils à bascule" },
    { id: 145, stars: 3, isGold: false, name: "Anticipation" },
    { id: 146, stars: 3, isGold: false, name: "Meilleurs amis pour toujours" },
    { id: 147, stars: 4, isGold: false, name: "Prix du champion" },
    { id: 148, stars: 4, isGold: true, name: "Une dernière photo" },
    { id: 149, stars: 4, isGold: true, name: "Repas pizza" },
    { id: 150, stars: 5, isGold: false, name: "Meilleure note" },
    { id: 151, stars: 5, isGold: false, name: "Câlins d'adieu" },
    { id: 152, stars: 5, isGold: false, name: "C'est l'heure" },
    { id: 153, stars: 5, isGold: true, name: "Enfin la liberté" },
    { id: 154, stars: 3, isGold: false, name: "Champs de lavande" },
    { id: 155, stars: 4, isGold: false, name: "L'heure du thé" },
    { id: 156, stars: 4, isGold: true, name: "Cueillette du matin" },
    { id: 157, stars: 4, isGold: true, name: "Bazar au marché" },
    { id: 158, stars: 5, isGold: false, name: "Joli pique-nique" },
    { id: 159, stars: 5, isGold: false, name: "Les marches de Vence" },
    { id: 160, stars: 5, isGold: true, name: "Sieste de l'après-midi" },
    { id: 161, stars: 5, isGold: true, name: "Voyage en vélo" },
    { id: 162, stars: 6, isGold: false, name: "Gordes en Provence" },
    { id: 163, stars: 4, isGold: false, name: "Flamant flottant" },
    { id: 164, stars: 4, isGold: true, name: "Sofia fait trempette" },
    { id: 165, stars: 4, isGold: true, name: "Kit de piscine" },
    { id: 166, stars: 5, isGold: false, name: "Ça pulse" },
    { id: 167, stars: 5, isGold: false, name: "Glace en folie !" },
    { id: 168, stars: 5, isGold: true, name: "Énergie solaire" },
    { id: 169, stars: 5, isGold: true, name: "Panique à la piscine" },
    { id: 170, stars: 6, isGold: false, name: "Bataille d'eau" },
    { id: 171, stars: 6, isGold: true, name: "Éclaboussures" },
    { id: 172, stars: 4, isGold: true, name: "Plans sucrés" },
    { id: 173, stars: 4, isGold: true, name: "Fabrication d'enseigne" },
    { id: 174, stars: 5, isGold: false, name: "Préparation en cours" },
    { id: 175, stars: 5, isGold: false, name: "Premier client" },
    { id: 176, stars: 5, isGold: true, name: "Ça vaut la pression" },
    { id: 177, stars: 5, isGold: true, name: "Remuage rapide" },
    { id: 178, stars: 6, isGold: false, name: "Réussite dorée" },
    { id: 179, stars: 6, isGold: false, name: "Jackpot !" },
    { id: 180, stars: 6, isGold: true, name: "Santé !" },
    { id: 181, stars: 3, isGold: false, name: "Plaisirs du festival" },
    { id: 182, stars: 4, isGold: false, name: "Haute en couleurs" },
    { id: 183, stars: 4, isGold: false, name: "Trio principal" },
    { id: 184, stars: 4, isGold: true, name: "Bain de foule" },
    { id: 185, stars: 4, isGold: true, name: "Énergie des idoles" },
    { id: 186, stars: 5, isGold: false, name: "Nation lumineuse" },
    { id: 187, stars: 5, isGold: false, name: "Succès commercial" },
    { id: 188, stars: 5, isGold: false, name: "Super fan" },
    { id: 189, stars: 5, isGold: true, name: "Tête d'affiche" },
    { id: 190, stars: 4, isGold: false, name: "La jet set de Go!" },
    { id: 191, stars: 4, isGold: true, name: "Première classe" },
    { id: 192, stars: 4, isGold: true, name: "Beaucoup de bagages" },
    { id: 193, stars: 5, isGold: false, name: "Yacht à gogo" },
    { id: 194, stars: 5, isGold: false, name: "Bonne direction" },
    { id: 195, stars: 5, isGold: false, name: "Capitaine Jon" },
    { id: 196, stars: 5, isGold: true, name: "Décollage luxueux" },
    { id: 197, stars: 5, isGold: true, name: "Reine du jet" },
    { id: 198, stars: 5, isGold: true, name: "Croisière Go!" }
];